### ISSUE TITLE
node using 100% CPU

### ISSUE THREAD

**Issue by yurtesen** [turtle0x1/LxdMosaic#213] opened 2020-06-09 06:45 UTC
I installed lxdMosaic using snap and `node` is using 100% cpu constantly
```
sudo snap install lxdmosaic --beta
```
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                     
1549456 root      20   0  596664  68788  27524 R 103.0   1.7   0:03.10 node          
```
```
$ ps auxw |grep node
root     1550005  112  2.1 613564 84860 ?        Rsl  09:45   0:09 node /snap/lxdmosaic/4/lxdmosaicNode/node/events.js
```

**Comment by turtle0x1** [comment] 2020-06-09 08:15
Snap is very new to me, its unpublished currently as a recommended way to install the app

If you need quick support / this is a production LXD setup, snap'd version of LXDMosaic is not what you need right now!

If not production, please keep snap & ill try to fix can you show `snap services lxdmosaic`

**Comment by yurtesen** [comment] 2020-06-09 19:55
I installed it using snap
```
sudo snap install --beta lxdmosaic
```

![image](https://user-images.githubusercontent.com/1926599/84193439-1f9d9180-aaa4-11ea-8d1b-237c207c90f2.png)

but that is what I get when I go to localhost (screenshot)

```
$ sudo snap services lxdmosaic
Service                   Startup   Current   Notes
lxdmosaic.apache          enabled   active    -
lxdmosaic.lxdmosaic-cron  disabled  inactive  timer-activated
lxdmosaic.lxdmosaic-node  enabled   active    -
lxdmosaic.mysql           enabled   active    -
lxdmosaic.php-fpm         enabled   active    -
```

**Comment by yurtesen** [comment] 2020-06-09 20:04
I now found this:
```
$ sudo systemctl status snap.lxdmosaic.mysql
● snap.lxdmosaic.mysql.service - Service for snap application lxdmosaic.mysql
     Loaded: loaded (/etc/systemd/system/snap.lxdmosaic.mysql.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-06-09 22:52:15 EEST; 11min ago
   Main PID: 1613402 (start_mysql)
      Tasks: 2 (limit: 4619)
     Memory: 35.0M
     CGroup: /system.slice/snap.lxdmosaic.mysql.service
             ├─1613402 /bin/sh /snap/lxdmosaic/4/bin/start_mysql
             └─1619143 sleep 1

Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614111]: RROR 2002 (HY000): Can't connect to local M
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614111]: RROR 2002 (HY000): Can't connect to local MySQL server th
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614112]: RROR 2002 (HY000): Can't connect to local MySQL server th
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614112]: RROR 2002 (HY000): Can't connect to local M
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614113]: RROR 2002 (HY000): Can't connect to local M
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614113]: RROR 2002 (HY000): Can't connect to local MySQL server th
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1613402]: RROR 2002 (HY000): Can't connect to
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614114]: RROR 2002 (HY000): Can't connect to
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614114]: * MySQL
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1613402]: * MySQL
```

**Comment by yurtesen** [comment] 2020-06-09 20:05
```
v$ sudo systemctl status snap.lxdmosaic.mysql
● snap.lxdmosaic.mysql.service - Service for snap application lxdmosaic.mysql
     Loaded: loaded (/etc/systemd/system/snap.lxdmosaic.mysql.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-06-09 22:52:15 EEST; 11min ago
   Main PID: 1613402 (start_mysql)
      Tasks: 2 (limit: 4619)
     Memory: 35.0M
     CGroup: /system.slice/snap.lxdmosaic.mysql.service
             ├─1613402 /bin/sh /snap/lxdmosaic/4/bin/start_mysql
             └─1619143 sleep 1

Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614111]: RROR 2002 (HY000): Can't connect to local M
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614111]: RROR 2002 (HY000): Can't connect to local MySQL server th
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614112]: RROR 2002 (HY000): Can't connect to local MySQL server th
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614112]: RROR 2002 (HY000): Can't connect to local M
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614113]: RROR 2002 (HY000): Can't connect to local M
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614113]: RROR 2002 (HY000): Can't connect to local MySQL server th
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1613402]: RROR 2002 (HY000): Can't connect to
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614114]: RROR 2002 (HY000): Can't connect to
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1614114]: * MySQL
Jun 09 22:52:22 hiboxdev lxdmosaic.mysql[1613402]: * MySQL
```

**Comment by yurtesen** [comment] 2020-06-09 20:07
```
$ sudo systemctl restart snap.lxdmosaic.mysql
$ sudo snap logs lxdmosaic.mysql
2020-06-09T20:06:32Z systemd[1]: Stopped Service for snap application lxdmosaic.mysql.
2020-06-09T20:06:32Z systemd[1]: Started Service for snap application lxdmosaic.mysql.
2020-06-09T20:06:32Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:32.828115Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2020-06-09T20:06:33Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:33.038155Z 0 [Warning] InnoDB: New log files created, LSN=45790
2020-06-09T20:06:33Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:33.079841Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2020-06-09T20:06:33Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:33.135300Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: b70b8f27-aa8c-11ea-b67f-0800271a338f.
2020-06-09T20:06:33Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:33.136277Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2020-06-09T20:06:33Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:33.259238Z 0 [Warning] CA certificate ca.pem is self signed.
2020-06-09T20:06:33Z lxdmosaic.mysql[1620204]: 2020-06-09T20:06:33.380487Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2020-06-09T20:06:35Z lxdmosaic.mysql[1620235]: Starting MySQL

**Comment by yurtesen** [comment] 2020-06-09 20:26
Hmm perhaps something is wrong with MySQL but I know nothing about snap programs so ... if you have any ideas, I can try...

**Comment by yurtesen** [comment] 2020-06-11 04:44
Where does MySQL write its database files to? I guess there is not much I can do right now but wait the next snap version of your package...

**Comment by turtle0x1** [comment] 2020-07-11 13:01
Im going to close this because the new version of the snap is very different, if you are still using (which I doubt you are) the next revision, it will completely reset the snap as I remove MySQL and some other components

**Closed by turtle0x1** 2020-07-11 13:01 UTC

**Comment by DragonEmbers** [comment] 2022-02-08 21:51
I'm not sure this issue is snap related... I didn't install via snap and I am experiencing the same issue across 2 different machines

**Comment by DragonEmbers** [comment] 2022-02-08 21:58
Further investigation for me and the 100% cpu from events.js is caused by pm2 continually restarting and this block of code:
```

if(!fs.existsSync(process.env.CERT_PATH)){
    console.log("waiting 10 seconds to see if a certificate gets created");
}

var startDate = new Date();

while (!fs.existsSync(process.env.CERT_PATH)) {
    var seconds = (new Date().getTime() - startDate.getTime()) / 1000;
    if(seconds > 10){
        break;
    }
}

if(!fs.existsSync(process.env.CERT_PATH)){
    console.log("couldn't read certificate file");
    process.exit(1);
}
```
