### ISSUE TITLE
Container Console not working in UI

### ISSUE THREAD

**Issue by Jonathan-Garber** [turtle0x1/LxdMosaic#476] opened 2022-03-10 23:54 UTC
**Describe the bug**
Could be my fault, not entirely sure. The 'Console' doesn't work on any of my test containers.
I did a clean container for Debian and Ubuntu and no matter what I try I cannot access 'console' via 'bash' from the web ui at all. The error on the side bar is 'Executing command - timeout waiting for websockets to connect'

**To Reproduce**
1. create new container
2. ensure container running
3. go to console and try any common shell e.g. 'bash'

**Expected behavior**
Expected shell session to open and be available.

**Screenshots**
N/A

**Host Server (please complete the following information):**
 - OS: Debian Bullseye
Installed LXDUI via SNAP

**Desktop
- OS: Windows 10 Pro
- Browser: Brave (shields off)

each container gets a valid IP, has internet access etc.
any idea or pointers here?

**Comment by turtle0x1** [comment] 2022-03-11 09:22
Can you try the candidate channel, the `latest/stable` branch is very old.

`snap refresh lxdmosaic --candidate`

That being said "Executing command - timeout waiting for websockets to connect" sounds like a LXD error not LXDMosaic (because we dont push error messages through "events" as far as I can remember)

**Comment by Jonathan-Garber** [comment] 2022-03-11 15:04
Interesting - Candidate release did indeed resolve the issue. Shell is now working as expected.
Thanks for that.

**Comment by turtle0x1** [comment] 2022-03-11 15:16
Excellent, going to close this. I'd like to release to `latest` but im stuck in a SNAP review queue :cry:

**Comment by Jonathan-Garber** [comment] 2022-03-11 15:21
I may have spoke to soon. The console connected but it seems to just disconnect after a few mins.
Is there anything I should be looking at in LXD that can be causing these cut offs?

**Comment by turtle0x1** [comment] 2022-03-11 15:27
Interesting, anything in the output of `journalctl -u snap.lxdmosaic.lxdmosaic-node.service` ?

I finish work in an hour or two so can try to reproduce then!

**Comment by Jonathan-Garber** [comment] 2022-03-11 15:32
Nothing that stands out - I can see where I stopped the snap for the update to candidate then upon restarting it shows a deprecation warning but thats it.
```
 DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC ...
```

**Comment by Jonathan-Garber** [comment] 2022-03-11 15:42
Just has this in there

![image](https://user-images.githubusercontent.com/2494571/157899774-8eebe8e9-9f60-4d78-85bb-e0e30fa72324.png)

**Comment by turtle0x1** [comment] 2022-03-11 15:46
Hmm was going to suggest its related to https://github.com/lxc/lxd/issues/10034

But if the op is still running in LXD its probably a bug our side.

Will take a look tonight

**Comment by turtle0x1** [comment] 2022-03-11 18:32
Weirdly opens happens in the SNAP but with no logs (as you suggested)

**Comment by turtle0x1** [comment] 2022-03-11 18:34
Its not just the console socket its the operations socket as well, I suspect the node server is crashing for some reason

**Comment by Jonathan-Garber** [comment] 2022-03-11 18:47
idk, I didn't dig too deep. Got pulled away for other work.

**Comment by turtle0x1** [comment] 2022-03-11 18:56
Its okay im just taking notes as I go

**Comment by turtle0x1** [comment] 2022-03-11 20:09
I hate SNAP, had enough not being able to get `console.log` to work - will look again tommorow

**Comment by turtle0x1** [comment] 2022-04-11 23:18
No longer seeing this behaviour on edge, please reopen if repeatable.

Its likely one of the following fixed it:

29ce0b58203478cc8d593d0860b56c2f4d4cd0a1
e7c7a826334c01d00dad72eb8e2e87c94e13ec9a

**Closed by turtle0x1** 2022-04-11 23:18 UTC
Labels: bug
