### ISSUE TITLE
Error sql-02

### ISSUE THREAD

**Issue by mdamic0** [turtle0x1/LxdMosaic#130] opened 2019-10-24 11:56 UTC
The installation works fine but when trying to use, there are sql errors thrown in the UI when trying to attach a host. I traced the issue and saw that in the sql-02 file the "JSON" field type for mariadb  doesn't seem to work. I changed it to LONGTEXT and reran it manually. I needed to also run the 03 sql file as well after 02. 
Everything seemed to work fine after that.

**Comment by turtle0x1** [comment] 2019-10-24 13:54
Hey are you running in centos or ubuntu (I assume centos)? 

Thanks for the bug report, maria DB isn't really supported (I only use MySQL) @trenb  can you please advise ?

**Comment by trenb** [comment] 2019-10-24 14:17
@mdamic0 - did you use the centos install script? Or did you install by hand? The centos install script worked with the last Mosaic release I used, however I had to give up LXD as there were too many issues with it, so went back to OpenVZ.

**Comment by turtle0x1** [comment] 2019-10-24 15:34
@trenb I think a custom repository will need to be added for centos as the version of maria db is behind 

You can see the file here ..

https://downloads.mariadb.org/mariadb/repositories/#distro=CentOS&distro_release=centos7-amd64--centos7&mirror=i3dnet&version=10.4

If you aren't interested in supporting the centos install script any more please let me know as i will remove support for it :smile:

**Comment by trenb** [comment] 2019-10-24 21:39
Yeah, I haven't looked at it since I provided it, so please remove support for it unless someone else is willing to take over. Sorry I can't be of further help on this!

**Comment by turtle0x1** [comment] 2019-10-26 03:05
hey @mdamic0 

I just fresh installed and had no problems? Did you follow the upgrade guide or ?

**Comment by mdamic0** [comment] 2019-10-28 11:16
It was a fresh install on a rpi3 and using rasbian. I followed the install guide for Ubuntu. It seems  I might have have mariadb installed already and the mysql commands ran on there. 
Sorry for the confusing, though for the most part it does work. As @trenb mentioned I believe I 
 installed an older mariadb version.

**Comment by mdamic0** [comment] 2019-10-28 11:19
Just curious @trenb what were the issues with LXD and what made you decide to go with OpenVZ?

**Comment by turtle0x1** [comment] 2019-10-28 12:16
Okay so you manually installed and because your version of maria db was behind this caused the issue ?

Its recommended LXDMosaic be installed in a container, so it can manage its own dependencies. 

As this was caused by a manual install (you already had maria db installed) im going to close this

**Closed by turtle0x1** 2019-10-28 12:16 UTC
Labels: bug, centos, good first issue

**Comment by trenb** [comment] 2019-10-28 14:36
@mdamic0 - Issues with cpu reporting within the container not being accurate on centos 7 host systems. Never got any interest from the lxcfs team to help track down the issue. Also, in order to migrate centos 5 and 6 containers to lxd, major changes were needed to the startup and shutdown process. Everything just works as expected with openvz, so stuck with it for now. Hopefully in the future, LXD will work better with centos 7 hosts, but it seems like that's not their priority.

**Comment by turtle0x1** [comment] 2019-10-28 14:40
@trenb  had you enabled the flags in lxcfs ?

**Comment by trenb** [comment] 2019-10-28 15:19
@turtle0x1 - yeah, I did. Problem only goes away when lxcfs isn't running at all. It's unfortunate, because I really like lxd, but without proper cpu accounting, it'll never work for me.

**Comment by turtle0x1** [comment] 2019-10-28 15:30
@trenb I am nearing that point, without CPU information nothing more can happen :man_shrugging:

**Comment by trenb** [comment] 2019-10-28 15:44
@turtle0x1 If you're having the same issue, please add to https://github.com/lxc/lxcfs/issues/284
