### ISSUE TITLE
Be able to start a remote console on the LXD host from the DashBoard

### ISSUE THREAD

**Issue by naz9ul** [turtle0x1/LxdMosaic#193] opened 2020-04-12 17:33 UTC
It will be very interesting to be able to open a ssh session to the lxd host from the dashboard

**Comment by vsltimkay** [comment] 2020-04-22 07:42
If this is a feature under consideration could I suggest that it would need AIM (authentication and identity management) in place first? At present the interface allows all users access to all containers, not ideal but _way_ less of an issue than any "standard" user having access to the hosts.

**Comment by turtle0x1** [comment] 2020-04-22 08:00
For the reasons you mention above & the work required, this feature is a long way off!

Also im not entirely sure how it fits in with LXD management and may fall out of scope

Its been asked for a few times so i havent closed it to prevent duplicates

**Comment by turtle0x1** [comment] 2020-12-30 19:56
@naz9ul im not sure if you even still use this software - but im closing this, its not on the immediate roadmap & would change the direction of this project!

**Closed by turtle0x1** 2020-12-30 19:56 UTC

**Comment by naz9ul** [comment] 2020-12-30 20:20
Yes still using it :-)  Maybe you should consider adding lxdmosaic to Cockpit "https://cockpit-project.org/" as a plugins there are already some plugins for other kind of container and vm

**Comment by turtle0x1** [comment] 2020-12-30 20:24
@naz9ul Great that your still using, let me know any problems / annoyances :smile:  the problem is, once I can manage a host over SSH there is no limit to what I can manage.

As i currently manage containers / VM's only via the LXD API, SSH control would be a radical shift - I will consider it, but not yet! :smile: 

thanks for updating
